production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
development:
  sessions:
    default:
      database: kelkdo_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: kelkdo_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false
